SELECT
  SUM(CASE WHEN ORD_DT <> LTRIM(RTRIM(ORD_DT)) THEN 1 ELSE 0 END) AS 앞뒤공백,
  SUM(CASE WHEN CHARINDEX(N'　', ORD_DT) > 0 THEN 1 ELSE 0 END)     AS 전각공백,
  SUM(CASE WHEN CHARINDEX(CHAR(10), ORD_DT) > 0 OR CHARINDEX(CHAR(13), ORD_DT) > 0
            OR CHARINDEX(CHAR(9), ORD_DT) > 0 THEN 1 ELSE 0 END)    AS 개행_탭,
  SUM(CASE WHEN PATINDEX('%[^0-9]%', ORD_DT) > 0 THEN 1 ELSE 0 END) AS 비숫자_혼입,
  SUM(CASE WHEN DATALENGTH(ORD_DT) <> LEN(ORD_DT) THEN 1 ELSE 0 END) AS 바이트_불일치
FROM APP.TB_ORDER;
-- 바이트_불일치: nvarchar 컬럼은 항상 2배라 무의미 — varchar 컬럼에서만 참고