-- PK 승격 후보 검증: 0행이어야 유일성 성립
SELECT ORD_NO, LINE_NO, COUNT(*) AS 건수
FROM   APP.TB_ORDER
GROUP  BY ORD_NO, LINE_NO
HAVING COUNT(*) > 1
ORDER  BY 건수 DESC;

-- PK는 NULL 불가 — 중복과 별도로 확인
SELECT COUNT(*) AS 키_NULL_건수
FROM   APP.TB_ORDER
WHERE  ORD_NO IS NULL OR LINE_NO IS NULL;