SELECT t.OWNER, t.TABLE_NAME
FROM   ALL_TABLES t
WHERE  t.OWNER IN ('APP', 'APP2')
  AND  NOT EXISTS (SELECT 1 FROM ALL_CONSTRAINTS c
                   WHERE  c.OWNER = t.OWNER AND c.TABLE_NAME = t.TABLE_NAME
                     AND  c.CONSTRAINT_TYPE = 'P')
ORDER  BY t.OWNER, t.TABLE_NAME;