SELECT t.TABLE_SCHEMA, t.TABLE_NAME
FROM   information_schema.TABLES t
WHERE  t.TABLE_SCHEMA IN ('APP', 'APP2') AND t.TABLE_TYPE = 'BASE TABLE'
  AND  NOT EXISTS (SELECT 1 FROM information_schema.TABLE_CONSTRAINTS c
                   WHERE  c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME
                     AND  c.CONSTRAINT_TYPE = 'PRIMARY KEY')
ORDER  BY t.TABLE_SCHEMA, t.TABLE_NAME;