-- 개인정보 마스킹 UPDATE — 개발·시험 사본에만. 운영 DB 에 돌리지 않는다. 되돌릴 수 없다(돌리기 전에 백업).
-- 방언 SQL Server, 표 3, 컬럼 13

-- COMTNEMPLYRINFO: USER_NM(이름) IHIDNUM(주민·외국인등록번호) MBTLNUM(전화번호) OFFM_TELNO(전화번호) EMAIL_ADRES(이메일) HOUSE_ADRES(주소)
UPDATE APP.COMTNEMPLYRINFO SET
    USER_NM = CASE WHEN LEN(USER_NM) <= 1 THEN REPLICATE('*', LEN(USER_NM)) ELSE LEFT(USER_NM, 1) + REPLICATE('*', LEN(USER_NM) - 1) END,
    IHIDNUM = CASE WHEN LEN(IHIDNUM) <= 6 THEN REPLICATE('*', LEN(IHIDNUM)) ELSE LEFT(IHIDNUM, 6) + REPLICATE('*', LEN(IHIDNUM) - 6) END,
    MBTLNUM = CASE WHEN LEN(MBTLNUM) <= 4 THEN REPLICATE('*', LEN(MBTLNUM)) ELSE REPLICATE('*', LEN(MBTLNUM) - 4) + RIGHT(MBTLNUM, 4) END,
    OFFM_TELNO = CASE WHEN LEN(OFFM_TELNO) <= 4 THEN REPLICATE('*', LEN(OFFM_TELNO)) ELSE REPLICATE('*', LEN(OFFM_TELNO) - 4) + RIGHT(OFFM_TELNO, 4) END,
    EMAIL_ADRES = CASE WHEN CHARINDEX('@', EMAIL_ADRES) > 1 THEN CASE WHEN LEN(LEFT(EMAIL_ADRES, CHARINDEX('@', EMAIL_ADRES) - 1)) <= 2 THEN REPLICATE('*', LEN(LEFT(EMAIL_ADRES, CHARINDEX('@', EMAIL_ADRES) - 1))) ELSE LEFT(LEFT(EMAIL_ADRES, CHARINDEX('@', EMAIL_ADRES) - 1), 2) + REPLICATE('*', LEN(LEFT(EMAIL_ADRES, CHARINDEX('@', EMAIL_ADRES) - 1)) - 2) END + SUBSTRING(EMAIL_ADRES, CHARINDEX('@', EMAIL_ADRES), LEN(EMAIL_ADRES)) ELSE CASE WHEN LEN(EMAIL_ADRES) <= 2 THEN REPLICATE('*', LEN(EMAIL_ADRES)) ELSE LEFT(EMAIL_ADRES, 2) + REPLICATE('*', LEN(EMAIL_ADRES) - 2) END END,
    HOUSE_ADRES = CASE WHEN LEN(HOUSE_ADRES) <= 6 THEN REPLICATE('*', LEN(HOUSE_ADRES)) ELSE LEFT(HOUSE_ADRES, 6) + REPLICATE('*', LEN(HOUSE_ADRES) - 6) END
WHERE USER_NM IS NOT NULL OR IHIDNUM IS NOT NULL OR MBTLNUM IS NOT NULL OR OFFM_TELNO IS NOT NULL OR EMAIL_ADRES IS NOT NULL OR HOUSE_ADRES IS NOT NULL;

-- EMPLOYEES: FIRST_NAME(이름) LAST_NAME(이름) EMAIL(이메일) PHONE_NUMBER(전화번호)
UPDATE APP.EMPLOYEES SET
    FIRST_NAME = CASE WHEN LEN(FIRST_NAME) <= 1 THEN REPLICATE('*', LEN(FIRST_NAME)) ELSE LEFT(FIRST_NAME, 1) + REPLICATE('*', LEN(FIRST_NAME) - 1) END,
    LAST_NAME = CASE WHEN LEN(LAST_NAME) <= 1 THEN REPLICATE('*', LEN(LAST_NAME)) ELSE LEFT(LAST_NAME, 1) + REPLICATE('*', LEN(LAST_NAME) - 1) END,
    EMAIL = CASE WHEN CHARINDEX('@', EMAIL) > 1 THEN CASE WHEN LEN(LEFT(EMAIL, CHARINDEX('@', EMAIL) - 1)) <= 2 THEN REPLICATE('*', LEN(LEFT(EMAIL, CHARINDEX('@', EMAIL) - 1))) ELSE LEFT(LEFT(EMAIL, CHARINDEX('@', EMAIL) - 1), 2) + REPLICATE('*', LEN(LEFT(EMAIL, CHARINDEX('@', EMAIL) - 1)) - 2) END + SUBSTRING(EMAIL, CHARINDEX('@', EMAIL), LEN(EMAIL)) ELSE CASE WHEN LEN(EMAIL) <= 2 THEN REPLICATE('*', LEN(EMAIL)) ELSE LEFT(EMAIL, 2) + REPLICATE('*', LEN(EMAIL) - 2) END END,
    PHONE_NUMBER = CASE WHEN LEN(PHONE_NUMBER) <= 4 THEN REPLICATE('*', LEN(PHONE_NUMBER)) ELSE REPLICATE('*', LEN(PHONE_NUMBER) - 4) + RIGHT(PHONE_NUMBER, 4) END
WHERE FIRST_NAME IS NOT NULL OR LAST_NAME IS NOT NULL OR EMAIL IS NOT NULL OR PHONE_NUMBER IS NOT NULL;

-- TB_PAY: ACNUTNO(계좌번호) CARD_NO(카드번호) BRTHDY(생년월일)
UPDATE APP.TB_PAY SET
    ACNUTNO = CASE WHEN LEN(ACNUTNO) <= 4 THEN REPLICATE('*', LEN(ACNUTNO)) ELSE REPLICATE('*', LEN(ACNUTNO) - 4) + RIGHT(ACNUTNO, 4) END,
    CARD_NO = CASE WHEN LEN(CARD_NO) <= 10 THEN REPLICATE('*', LEN(CARD_NO)) ELSE LEFT(CARD_NO, 6) + REPLICATE('*', LEN(CARD_NO) - 10) + RIGHT(CARD_NO, 4) END,
    BRTHDY = CASE WHEN LEN(BRTHDY) <= 4 THEN REPLICATE('*', LEN(BRTHDY)) ELSE LEFT(BRTHDY, 4) + REPLICATE('*', LEN(BRTHDY) - 4) END
WHERE ACNUTNO IS NOT NULL OR CARD_NO IS NOT NULL OR BRTHDY IS NOT NULL;
