-- 개인정보 마스킹 UPDATE — 개발·시험 사본에만. 운영 DB 에 돌리지 않는다. 되돌릴 수 없다(돌리기 전에 백업).
-- 방언 Oracle, 표 3, 컬럼 13

-- COMTNEMPLYRINFO: USER_NM(이름) IHIDNUM(주민·외국인등록번호) MBTLNUM(전화번호) OFFM_TELNO(전화번호) EMAIL_ADRES(이메일) HOUSE_ADRES(주소)
UPDATE APP.COMTNEMPLYRINFO SET
    USER_NM = CASE WHEN LENGTH(USER_NM) <= 1 THEN RPAD('*', LENGTH(USER_NM), '*') ELSE SUBSTR(USER_NM, 1, 1) || RPAD('*', LENGTH(USER_NM) - 1, '*') END,
    IHIDNUM = CASE WHEN LENGTH(IHIDNUM) <= 6 THEN RPAD('*', LENGTH(IHIDNUM), '*') ELSE SUBSTR(IHIDNUM, 1, 6) || RPAD('*', LENGTH(IHIDNUM) - 6, '*') END,
    MBTLNUM = CASE WHEN LENGTH(MBTLNUM) <= 4 THEN RPAD('*', LENGTH(MBTLNUM), '*') ELSE RPAD('*', LENGTH(MBTLNUM) - 4, '*') || SUBSTR(MBTLNUM, -4) END,
    OFFM_TELNO = CASE WHEN LENGTH(OFFM_TELNO) <= 4 THEN RPAD('*', LENGTH(OFFM_TELNO), '*') ELSE RPAD('*', LENGTH(OFFM_TELNO) - 4, '*') || SUBSTR(OFFM_TELNO, -4) END,
    EMAIL_ADRES = CASE WHEN INSTR(EMAIL_ADRES, '@') > 1 THEN CASE WHEN LENGTH(SUBSTR(EMAIL_ADRES, 1, INSTR(EMAIL_ADRES, '@') - 1)) <= 2 THEN RPAD('*', LENGTH(SUBSTR(EMAIL_ADRES, 1, INSTR(EMAIL_ADRES, '@') - 1)), '*') ELSE SUBSTR(SUBSTR(EMAIL_ADRES, 1, INSTR(EMAIL_ADRES, '@') - 1), 1, 2) || RPAD('*', LENGTH(SUBSTR(EMAIL_ADRES, 1, INSTR(EMAIL_ADRES, '@') - 1)) - 2, '*') END || SUBSTR(EMAIL_ADRES, INSTR(EMAIL_ADRES, '@')) ELSE CASE WHEN LENGTH(EMAIL_ADRES) <= 2 THEN RPAD('*', LENGTH(EMAIL_ADRES), '*') ELSE SUBSTR(EMAIL_ADRES, 1, 2) || RPAD('*', LENGTH(EMAIL_ADRES) - 2, '*') END END,
    HOUSE_ADRES = CASE WHEN LENGTH(HOUSE_ADRES) <= 6 THEN RPAD('*', LENGTH(HOUSE_ADRES), '*') ELSE SUBSTR(HOUSE_ADRES, 1, 6) || RPAD('*', LENGTH(HOUSE_ADRES) - 6, '*') END
WHERE USER_NM IS NOT NULL OR IHIDNUM IS NOT NULL OR MBTLNUM IS NOT NULL OR OFFM_TELNO IS NOT NULL OR EMAIL_ADRES IS NOT NULL OR HOUSE_ADRES IS NOT NULL;

-- EMPLOYEES: FIRST_NAME(이름) LAST_NAME(이름) EMAIL(이메일) PHONE_NUMBER(전화번호)
UPDATE APP.EMPLOYEES SET
    FIRST_NAME = CASE WHEN LENGTH(FIRST_NAME) <= 1 THEN RPAD('*', LENGTH(FIRST_NAME), '*') ELSE SUBSTR(FIRST_NAME, 1, 1) || RPAD('*', LENGTH(FIRST_NAME) - 1, '*') END,
    LAST_NAME = CASE WHEN LENGTH(LAST_NAME) <= 1 THEN RPAD('*', LENGTH(LAST_NAME), '*') ELSE SUBSTR(LAST_NAME, 1, 1) || RPAD('*', LENGTH(LAST_NAME) - 1, '*') END,
    EMAIL = CASE WHEN INSTR(EMAIL, '@') > 1 THEN CASE WHEN LENGTH(SUBSTR(EMAIL, 1, INSTR(EMAIL, '@') - 1)) <= 2 THEN RPAD('*', LENGTH(SUBSTR(EMAIL, 1, INSTR(EMAIL, '@') - 1)), '*') ELSE SUBSTR(SUBSTR(EMAIL, 1, INSTR(EMAIL, '@') - 1), 1, 2) || RPAD('*', LENGTH(SUBSTR(EMAIL, 1, INSTR(EMAIL, '@') - 1)) - 2, '*') END || SUBSTR(EMAIL, INSTR(EMAIL, '@')) ELSE CASE WHEN LENGTH(EMAIL) <= 2 THEN RPAD('*', LENGTH(EMAIL), '*') ELSE SUBSTR(EMAIL, 1, 2) || RPAD('*', LENGTH(EMAIL) - 2, '*') END END,
    PHONE_NUMBER = CASE WHEN LENGTH(PHONE_NUMBER) <= 4 THEN RPAD('*', LENGTH(PHONE_NUMBER), '*') ELSE RPAD('*', LENGTH(PHONE_NUMBER) - 4, '*') || SUBSTR(PHONE_NUMBER, -4) END
WHERE FIRST_NAME IS NOT NULL OR LAST_NAME IS NOT NULL OR EMAIL IS NOT NULL OR PHONE_NUMBER IS NOT NULL;

-- TB_PAY: ACNUTNO(계좌번호) CARD_NO(카드번호) BRTHDY(생년월일)
UPDATE APP.TB_PAY SET
    ACNUTNO = CASE WHEN LENGTH(ACNUTNO) <= 4 THEN RPAD('*', LENGTH(ACNUTNO), '*') ELSE RPAD('*', LENGTH(ACNUTNO) - 4, '*') || SUBSTR(ACNUTNO, -4) END,
    CARD_NO = CASE WHEN LENGTH(CARD_NO) <= 10 THEN RPAD('*', LENGTH(CARD_NO), '*') ELSE SUBSTR(CARD_NO, 1, 6) || RPAD('*', LENGTH(CARD_NO) - 10, '*') || SUBSTR(CARD_NO, -4) END,
    BRTHDY = CASE WHEN LENGTH(BRTHDY) <= 4 THEN RPAD('*', LENGTH(BRTHDY), '*') ELSE SUBSTR(BRTHDY, 1, 4) || RPAD('*', LENGTH(BRTHDY) - 4, '*') END
WHERE ACNUTNO IS NOT NULL OR CARD_NO IS NOT NULL OR BRTHDY IS NOT NULL;
