-- 개인정보 마스킹 UPDATE — 개발·시험 사본에만. 운영 DB 에 돌리지 않는다. 되돌릴 수 없다(돌리기 전에 백업).
-- 방언 MySQL/MariaDB, 표 3, 컬럼 13

-- COMTNEMPLYRINFO: USER_NM(이름) IHIDNUM(주민·외국인등록번호) MBTLNUM(전화번호) OFFM_TELNO(전화번호) EMAIL_ADRES(이메일) HOUSE_ADRES(주소)
UPDATE APP.COMTNEMPLYRINFO SET
    USER_NM = CASE WHEN CHAR_LENGTH(USER_NM) <= 1 THEN REPEAT('*', CHAR_LENGTH(USER_NM)) ELSE CONCAT(LEFT(USER_NM, 1), REPEAT('*', CHAR_LENGTH(USER_NM) - 1)) END,
    IHIDNUM = CASE WHEN CHAR_LENGTH(IHIDNUM) <= 6 THEN REPEAT('*', CHAR_LENGTH(IHIDNUM)) ELSE CONCAT(LEFT(IHIDNUM, 6), REPEAT('*', CHAR_LENGTH(IHIDNUM) - 6)) END,
    MBTLNUM = CASE WHEN CHAR_LENGTH(MBTLNUM) <= 4 THEN REPEAT('*', CHAR_LENGTH(MBTLNUM)) ELSE CONCAT(REPEAT('*', CHAR_LENGTH(MBTLNUM) - 4), RIGHT(MBTLNUM, 4)) END,
    OFFM_TELNO = CASE WHEN CHAR_LENGTH(OFFM_TELNO) <= 4 THEN REPEAT('*', CHAR_LENGTH(OFFM_TELNO)) ELSE CONCAT(REPEAT('*', CHAR_LENGTH(OFFM_TELNO) - 4), RIGHT(OFFM_TELNO, 4)) END,
    EMAIL_ADRES = CASE WHEN LOCATE('@', EMAIL_ADRES) > 1 THEN CONCAT(CASE WHEN CHAR_LENGTH(LEFT(EMAIL_ADRES, LOCATE('@', EMAIL_ADRES) - 1)) <= 2 THEN REPEAT('*', CHAR_LENGTH(LEFT(EMAIL_ADRES, LOCATE('@', EMAIL_ADRES) - 1))) ELSE CONCAT(LEFT(LEFT(EMAIL_ADRES, LOCATE('@', EMAIL_ADRES) - 1), 2), REPEAT('*', CHAR_LENGTH(LEFT(EMAIL_ADRES, LOCATE('@', EMAIL_ADRES) - 1)) - 2)) END, SUBSTRING(EMAIL_ADRES, LOCATE('@', EMAIL_ADRES))) ELSE CASE WHEN CHAR_LENGTH(EMAIL_ADRES) <= 2 THEN REPEAT('*', CHAR_LENGTH(EMAIL_ADRES)) ELSE CONCAT(LEFT(EMAIL_ADRES, 2), REPEAT('*', CHAR_LENGTH(EMAIL_ADRES) - 2)) END END,
    HOUSE_ADRES = CASE WHEN CHAR_LENGTH(HOUSE_ADRES) <= 6 THEN REPEAT('*', CHAR_LENGTH(HOUSE_ADRES)) ELSE CONCAT(LEFT(HOUSE_ADRES, 6), REPEAT('*', CHAR_LENGTH(HOUSE_ADRES) - 6)) END
WHERE USER_NM IS NOT NULL OR IHIDNUM IS NOT NULL OR MBTLNUM IS NOT NULL OR OFFM_TELNO IS NOT NULL OR EMAIL_ADRES IS NOT NULL OR HOUSE_ADRES IS NOT NULL;

-- EMPLOYEES: FIRST_NAME(이름) LAST_NAME(이름) EMAIL(이메일) PHONE_NUMBER(전화번호)
UPDATE APP.EMPLOYEES SET
    FIRST_NAME = CASE WHEN CHAR_LENGTH(FIRST_NAME) <= 1 THEN REPEAT('*', CHAR_LENGTH(FIRST_NAME)) ELSE CONCAT(LEFT(FIRST_NAME, 1), REPEAT('*', CHAR_LENGTH(FIRST_NAME) - 1)) END,
    LAST_NAME = CASE WHEN CHAR_LENGTH(LAST_NAME) <= 1 THEN REPEAT('*', CHAR_LENGTH(LAST_NAME)) ELSE CONCAT(LEFT(LAST_NAME, 1), REPEAT('*', CHAR_LENGTH(LAST_NAME) - 1)) END,
    EMAIL = CASE WHEN LOCATE('@', EMAIL) > 1 THEN CONCAT(CASE WHEN CHAR_LENGTH(LEFT(EMAIL, LOCATE('@', EMAIL) - 1)) <= 2 THEN REPEAT('*', CHAR_LENGTH(LEFT(EMAIL, LOCATE('@', EMAIL) - 1))) ELSE CONCAT(LEFT(LEFT(EMAIL, LOCATE('@', EMAIL) - 1), 2), REPEAT('*', CHAR_LENGTH(LEFT(EMAIL, LOCATE('@', EMAIL) - 1)) - 2)) END, SUBSTRING(EMAIL, LOCATE('@', EMAIL))) ELSE CASE WHEN CHAR_LENGTH(EMAIL) <= 2 THEN REPEAT('*', CHAR_LENGTH(EMAIL)) ELSE CONCAT(LEFT(EMAIL, 2), REPEAT('*', CHAR_LENGTH(EMAIL) - 2)) END END,
    PHONE_NUMBER = CASE WHEN CHAR_LENGTH(PHONE_NUMBER) <= 4 THEN REPEAT('*', CHAR_LENGTH(PHONE_NUMBER)) ELSE CONCAT(REPEAT('*', CHAR_LENGTH(PHONE_NUMBER) - 4), RIGHT(PHONE_NUMBER, 4)) END
WHERE FIRST_NAME IS NOT NULL OR LAST_NAME IS NOT NULL OR EMAIL IS NOT NULL OR PHONE_NUMBER IS NOT NULL;

-- TB_PAY: ACNUTNO(계좌번호) CARD_NO(카드번호) BRTHDY(생년월일)
UPDATE APP.TB_PAY SET
    ACNUTNO = CASE WHEN CHAR_LENGTH(ACNUTNO) <= 4 THEN REPEAT('*', CHAR_LENGTH(ACNUTNO)) ELSE CONCAT(REPEAT('*', CHAR_LENGTH(ACNUTNO) - 4), RIGHT(ACNUTNO, 4)) END,
    CARD_NO = CASE WHEN CHAR_LENGTH(CARD_NO) <= 10 THEN REPEAT('*', CHAR_LENGTH(CARD_NO)) ELSE CONCAT(LEFT(CARD_NO, 6), REPEAT('*', CHAR_LENGTH(CARD_NO) - 10), RIGHT(CARD_NO, 4)) END,
    BRTHDY = CASE WHEN CHAR_LENGTH(BRTHDY) <= 4 THEN REPEAT('*', CHAR_LENGTH(BRTHDY)) ELSE CONCAT(LEFT(BRTHDY, 4), REPEAT('*', CHAR_LENGTH(BRTHDY) - 4)) END
WHERE ACNUTNO IS NOT NULL OR CARD_NO IS NOT NULL OR BRTHDY IS NOT NULL;
